#logging:
#  level:
#    com: off
#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  shardingsphere:
#    datasource:
#      names: online-retailer0, online-retailer1
#      common:
#        type: com.zaxxer.hikari.HikariDataSource
#      online-retailer0:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/online_retailer0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#      online-retailer1:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/online_retailer1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#    sharding:
#      tables:
#        dt_order:
#          actual-data-nodes: online_retailer0.dt_order$->{0..15}, online_retailer1.dt_order$->{0..15}
#          key-generator:
#            column: order_id
#            type: SNOWFLAKE
#          database-strategy:
#            inline:
#              sharding-column: buyer_id
#              algorithm-expression: online_retailer$->{buyer_id % 2}
#          table-strategy:
#            inline:
#              sharding-column: order_id
#              algorithm-expression: dt_order$->{order_id % 16}
#      tables:
#        myorder:
#          actual-data-nodes: online_retailer$->{0..1}.dt_order$->{0..15}
#          tableStrategy:
#            standard:
#              shardingColumn: order_id
#              shardingAlgorithmName: order-id-inline
#          keyGenerateStrategy:
#            column: order_id
#            keyGeneratorName: snowflake
#      default-database-strategy:
#        standard:
#          shardingColumn: buyer_id
#          shardingAlgorithmName: database-inline
#      shardingAlgorithms:
#        database-inline:
#          type: INLINE
#          props:
#            algorithm-expression: online_retailer$->{buyer_id % 2}
#        order-id-inline:
#          type: INLINE
#          props:
#            algorithm-expression: dt_order$->{order_id % 16}
#      keyGenerators:
#        snowflake:
#          type: SNOWFLAKE
#          props:
#            worker-id: 123
